// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Item struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Quantity int64  `json:"quantity"`
}

type Order struct {
	ID        int64     `json:"id"`
	ItemID    int64     `json:"item_id"`
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}
