// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	GetItem(ctx context.Context, id int64) (Item, error)
	GetItemForUpdate(ctx context.Context, id int64) (Item, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	UpdateItemQuantity(ctx context.Context, arg UpdateItemQuantityParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
